name: lexicon
description: Core library for parsing Lexicon in the AT Protocol standard.
version: 1.0.2
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/packages/lexicon
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  nsid: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.2
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^2.4.7
  import_sorter: ^4.6.0
