name: atproto
description: The most famous and powerful Dart/Flutter library for AT Protocol.
version: 1.0.7
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/packages/atproto
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=3.6.0 <4.0.0"

topics:
  - atproto
  - bluesky
  - api

dependencies:
  atproto_core: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.2
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^2.4.7
  import_sorter: ^4.6.0

  atproto_test:
    path: ../atproto_test
